### ISSUE TITLE
elan0608 only have  single  touch

### ISSUE THREAD

**Issue by penghubingzhou** [kprinssu/VoodooI2CELAN#9]
Hi，I have helped a people  who have elan0608. He can only have single touch with i2chid in interrupt mode. So I  tried to use i2celan as satellite  kext. But it can only  have  mutitouch preference in syspref ,still no multitouch. Checked with  Fingermgmt and it can only detect  single  touch .

**Comment by kprinssu** [comment]
I suggest that the person who has the ELAN0608 spin up a Linux Live USB and try doing a lspci or similar command to figure out which kernel module is loading for the trackpad.

I suspect that the trackpad is probably using the PTP protocol instead of ELAN's proprietary one. Additionally, instead of creating a Github ticket for compatibility questions, could ping the Gitter.im channel?

**Comment by penghubingzhou** [comment]
> I suggest that the person who has the ELAN0608 spin up a Linux Live USB and try doing a lspci or similar command to figure out which kernel module is loading for the trackpad.
> 
> I suspect that the trackpad is probably using the PTP protocol instead of ELAN's proprietary one. Additionally, instead of creating a Github ticket for compatibility questions, could ping the Gitter.im channel?

Ok I ll  try  to persuade  him  to ping  gitter.im and  tell him  about  that . Thks  for  reply.

**Comment by kprinssu** [comment]
I’ll close the issue for now considering it’s not related to a bug with kernel extension. Feel free to reopen if there really is an issue with the kernel extension.
